---
title: "finalproject"
format: html
editor: visual
---
```{r}
library(data.table)
library(ggplot2)
library(stringr)
```

```{r}
#load datasets 
arrests <- read.csv('Arrests_All.csv')
charges <- read.csv('Charges_All.csv')
```


### EDA

```{r}
colnames(arrests)
arrests <- arrests[c("SEX", "CURRENT.STATUS", "GO.NO", "RACE", "PIN", "ETHNICITY", "ARREST.REASON", "SUMMARY.OF.FACTS", "AGE", "ARREST.DATE", "ARREST.TYPE")]
head(arrests, 3) 
```


```{r}
print("sex")
print(table(arrests$SEX))
print("race")
print(table(arrests$RACE))
print("ethnicity")
print(table(arrests$ETHNICITY)) #has slightly more NA values
print("age")
print(table(arrests$AGE)) #split into decades 
print("status")
print(table(arrests$CURRENT.STATUS)) 
#cited -> either booked (jail) or cited (assinged court date + released)
```


```{r}
colnames(charges) 
charges <- charges[c("GO.NO", "PIN", "STATUTE", "OFFENSE.DATE", "SEVERITY", "WARRANT.NUMBER")]
head(charges, 3) #severity -> regular criminal classes (felony, misdemeanor, etc.)
```

```{r}
sum(is.na(arrests$PIN))
arrests[arrests$PIN == "", ]
sum(is.na(charges$PIN)) 
charges[charges$PIN == "", ]
```

```{r}
sum(is.na(arrests$GO.NO))
arrests[arrests$GO.NO == "", ]
sum(is.na(charges$GO.NO)) 
charges[charges$GO.NO == "", ]
```

```{r}
#sum(is.na(arrests$PIN)) #drop
arrests <- arrests[!is.na(arrests$PIN), ]


sm_a <- arrests[arrests$GO.NO == "", ] #warrants 
```

```{r}
table(sm_a$CURRENT.STATUS)
```

```{r}
sm_c <- charges[(charges$GO.NO == ""), ]

```

```{r}
arrests[arrests$PIN == 5046796, ] #6 where GO.NO is blank
```

```{r}
charges[charges$PIN == 5046796, ] #2 where GO.NO is blank
```

```{r}
arrest_charges_sm <- merge(sm_a, sm_c, by = c("PIN"))
arrest_charges_sm
```

```{r}
#issue because some rows in both arrests and charges do not have GO.NO 
#will fix in next section
```

### Merging

```{r}
sum(is.na(arrests$ARREST.REASON))

sum(is.na(charges$STATUTE))

#a complete row will have both of these not be null
```

```{r}
#arrests AND charge both have GO.NO (incident) and a PIN (person) 
setDT(arrests)
setDT(charges)


arrest_charges <- merge(arrests, charges, by = c("GO.NO", "PIN"), all.x = TRUE, all.y = TRUE)
colnames(arrest_charges)
nrow(arrest_charges)
```



```{r}
arrest_charges[(arrest_charges$PIN == 5046796) & (arrest_charges$GO.NO == ""), ]
#some are joined only by PIN number (person)
#all of these are matched together, when only the final two should 
```

```{r}
#fix date issue:
sample(arrest_charges$OFFENSE.DATE, 10, FALSE)
```

```{r}
sample(arrest_charges$ARREST.DATE, 10, FALSE)
```

```{r}
#match arrest date with offense date format 

#start with month
arrest_charges$ARREST.DATE_FIXED <- sub("^0", "", arrest_charges$ARREST.DATE)

#then day
arrest_charges$ARREST.DATE_FIXED <- sub("^(.+)/0", "\\1/", arrest_charges$ARREST.DATE_FIXED)

#then year
arrest_charges$ARREST.DATE_FIXED <- sub("/(\\d{2})$", "/20\\1", arrest_charges$ARREST.DATE_FIXED)
```

```{r}
sample(arrest_charges$ARREST.DATE_FIXED, 10, FALSE) #looks good
```

```{r}
#unmatch rows where the dates do not align (remove corresponding charge info):
#find where GO.NO is blank -> Check if dates align (fix dates)
#if dates do not align -> remove information about the charge (statute) since it is incorrect 
arrest_charges[GO.NO == "" & ARREST.DATE_FIXED != OFFENSE.DATE, STATUTE := NA]
```

```{r}
arrest_charges[(arrest_charges$PIN == 5046796) & (arrest_charges$GO.NO == ""), ]
```

```{r}
#remove duplicate arrest information 
#remove duplicates of PIN, ARREST_DATE, SUMMARY.OF.FACTS
arrest_charges <- rbind(
  unique(arrest_charges[GO.NO == ""], 
         by = c("PIN", "SUMMARY.OF.FACTS", "ARREST.REASON")),
  arrest_charges[GO.NO != ""]
)
```


```{r}
notnull <- arrest_charges[(!is.na(arrest_charges$STATUTE)) & (!is.na(arrest_charges$ARREST.REASON)), ]
head(notnull)
nrow(notnull)
```


```{r}
#there may be multiple charges for 1 arrest 
#GIVEN an arrest has at least one corresponding charge, what is the average charges / arrest? 

print("avg. number of charges")
notnull[, .(num_charges = .N), by = c("PIN", "SUMMARY.OF.FACTS", "ARREST.DATE")] |>
  _[, num_charges] |>
  mean()
```

```{r}
#charges without an arrest
empty_charges <- arrest_charges[(!is.na(arrest_charges$STATUTE)) & (is.na(arrest_charges$ARREST.REASON)), ]
nrow(empty_charges)

#check how many are warrants
nrow(empty_charges[WARRANT.NUMBER != "", ])

#~3/4 have warrant numbers
```



```{r}
#arrests with no charges (arrest reason without a statute) -> investigate
#try matching the empty arrests by joining the date + PIN with charges

empty_arrests <- arrest_charges[(is.na(arrest_charges$STATUTE)) & (!is.na(arrest_charges$ARREST.REASON)), ]
empty_arrests
```

```{r}
#all of these also have matches 
empty_arrests[PIN == 327937, ]
```

```{r}
charges[PIN == 327937, ]
```

```{r}
cols <- c("STATUTE", "OFFENSE.DATE", "SEVERITY", "WARRANT.NUMBER")
empty_arrests[, (cols) := NULL]
```

```{r}
leftover_arrests_with_charges <- merge(empty_arrests, charges, by.x = c("PIN","ARREST.DATE_FIXED"),
                                       by.y = c("PIN", "OFFENSE.DATE"), all.x = TRUE, all.y = FALSE)
```

```{r}
small_empty_arrests <- leftover_arrests_with_charges[is.na(STATUTE), ] 
cols <- c("STATUTE", "SEVERITY", "WARRANT.NUMBER", "GO.NO.y")
#remove cols because they don't exist anyway
small_empty_arrests[, (cols) := NULL]
small_empty_arrests #truly the arrests without charges
```

```{r}
#need final arrests + charges (arrest_charges)
#bind original notnull + leftovers that are not part of small_empty_arrests 
#final data.table to compare with
true_leftover_arrests_with_charges <-leftover_arrests_with_charges[!is.na(STATUTE), ]
```

```{r}
colnames(notnull)
```

```{r}
colnames(true_leftover_arrests_with_charges)
true_leftover_arrests_with_charges[, GO.NO.x := NULL]
setnames(true_leftover_arrests_with_charges, "GO.NO.y", "GO.NO")
true_leftover_arrests_with_charges[, OFFENSE.DATE := ARREST.DATE_FIXED]
```

```{r}
final_arrest_charges <- rbind(true_leftover_arrests_with_charges, notnull)
final_arrest_charges
```


### Compare Groups

#### Age

```{r}
hist(small_empty_arrests[, AGE])
mean(small_empty_arrests[, AGE], na.rm = TRUE)
```

```{r}
hist(final_arrest_charges[, AGE])
mean(final_arrest_charges[, AGE], na.rm = TRUE)

```

#### Sex 

```{r}
table(small_empty_arrests[, SEX]) / nrow(small_empty_arrests) * 100

```

```{r}
table(final_arrest_charges[, SEX]) / nrow(final_arrest_charges) * 100
```


#### Race

```{r}
nrow(small_empty_arrests[RACE != ETHNICITY, ])
nrow(small_empty_arrests[RACE == "", ])
nrow(small_empty_arrests[ETHNICITY == "", ])
#race is less empty than ethnicity
```

```{r}
race_codes <- read.csv('Race_Codes.csv')
head(race_codes, 1)
setnames(small_empty_arrests, "RACE", "CODE")
```

```{r}
small_empty_arrests[1]
```

```{r}
race_small_empty_arrests <- merge(small_empty_arrests, race_codes, by = "CODE")
```

```{r}
race_small_empty_arrests[, .N, by = RACE]
```

```{r}
race_groups <- read.csv('race_groups.csv')
race_small_empty_arrests <- merge(race_small_empty_arrests, race_groups, by = "RACE")
race_small_empty_arrests[, .N, by = RACE_GROUP]
```


```{r}
#perform similar actions to "regular" dt
setnames(final_arrest_charges, "RACE", "CODE")
race_final_arrest_charges <- merge(final_arrest_charges, race_codes, by = "CODE")
race_final_arrest_charges <- merge(race_final_arrest_charges, race_groups, by = "RACE")
race_final_arrest_charges[, .N, by = RACE_GROUP]
```


```{r}
#get proportions
race_small_prop <- race_small_empty_arrests[, .N, by = RACE_GROUP] |>
  _[, prop := N/nrow(race_small_empty_arrests)]

race_prop <- race_final_arrest_charges[, .N, by = RACE_GROUP] |>
  _[, prop := N/nrow(race_final_arrest_charges)]
```


```{r}
race_small_prop[, type := "No Charges"]
race_prop[, type := "With Charges"]

race_prop_all <- rbind(race_small_prop, race_prop)
```

```{r}

ggplot(race_prop_all, aes(x = RACE_GROUP, y = prop, fill = type)) +
  geom_col(position = "dodge") +
  coord_flip() +
  scale_fill_manual(values = c("steelblue", "salmon")) +
  labs(y = "Proportion", x = "Race Group", fill = "Charge Type")
#seems to be a difference

ggsave(
  filename = "race_proportions.png",
  width = 9,
  height = 4,
  dpi = 300
)
```

```{r}

print(race_small_prop)

```

```{r}

print(race_prop)

```


### Permutation Test


```{r}
#total difference in proportions (overall t_stat)
race_prop_all_h <- merge(race_prop, race_small_prop, by = c("RACE_GROUP"))
race_prop_all_h[, diff_prop := abs(prop.x - prop.y)]
t_stat <- sum(race_prop_all_h[, diff_prop]) 
```

```{r}
#test statistic: sum difference in proportions 

#run a test: randomly sample nrows(small) from the large and see how frequent this sample 

count <-  rep(NA, 10000)
t_stats <- rep(-1, 10000)

for (i in 1:10000) {
  #sample 
  sample <- race_final_arrest_charges[sample(.N,  nrow(race_small_empty_arrests))]
  sample_props <- sample[, .N, by = RACE_GROUP] |>
  _[, prop := N/nrow(sample)]
  
  #calculate current t-stat
  t_stat_prop <- merge(sample_props, race_prop, by = c("RACE_GROUP"))
  t_stat_prop[, diff_prop := abs(prop.x - prop.y)]
  curr_t_stat <- sum(t_stat_prop[, diff_prop]) 
  
  #compare
  count[i] <- curr_t_stat >= t_stat
  t_stats[i] <- curr_t_stat
  
}

#want to test the likelihood of it being random that there is this difference in proportions
```


```{r}
p_val <- mean(count)
p_val
```


### Incidents 

```{r}
hlm <- race_small_empty_arrests[RACE_GROUP == "HISPANIC/LATIN/MEXICAN", ]
hlm
#this group had the largest difference 
#more and highest proportion arrests without charges 
```

```{r}
nrow(hlm[GO.NO.x != "", ]) / nrow(hlm) #most do (should) have a corresponding incident
hlm <- hlm[GO.NO.x != "", ]
```

```{r}
#instructions from Kaggle
incidents <- read.csv('Incidents_All.csv')
```

```{r}
incidents
```

```{r}
hlm$INCIDENT.NO <- sub("^SJ.{4}", "", hlm$GO.NO.x) #some are warrants and others
hlm$INCIDENT.NO <- gsub("[^0-9]", "", hlm$INCIDENT.NO )
hlm$INCIDENT.NO <- as.integer(hlm$INCIDENT.NO)

#hlm$INCIDENT.NO
```


```{r}
hlm_incidents <- merge(hlm, incidents, by = "INCIDENT.NO")
hlm_incidents #about 1,000 rows with matching incidents
#a little more than a quarter of the total hlm rows without a charge
```



```{r}
sort(table(hlm_incidents[, INCIDENT.DESCRIPTION]), decreasing = TRUE)[1:10]
#most frequent incidents 
```

